[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
box_2024 = "6ZHVd3e9rykT1WeMrAxbs7ur8hkrwXwDn7VV1eBuQyDW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/tabatrung/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
