[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
box_2024 = "72FjLwoRaTuaCeWUWBFYGLZo53tx99Wvb3FmE8jyhaqb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/tabatrung/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
